ApparelStoreUserPortal/Models/FeedBacks.cs
using System;
using System.Collections.Generic;

namespace ApparelStoreUserPortal.Models
{
    public partial class FeedBacks
    {
        public int FeedBackId { get; set; }
        public int CustomerId { get; set; }
        public string Message { get; set; }

        public Customers Customer { get; set; }
    }
}

ApparelStoreUserPortal/Controllers/DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApparelStoreUserPortal.Helper;
using ApparelStoreUserPortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace ApparelStoreUserPortal.Controllers
{
    public class DetailController : Controller
    {
        private readonly OnlineApparelStoreDbContext context;
        public DetailController(OnlineApparelStoreDbContext _context)
        {
            context = _context;
        }
        [Route("index")]
        public IActionResult Index()
         {
                var products = context.Products.ToList();
                return View(products);
         }
        
        [Route("display/{id}")]
        public IActionResult Display(int id)
        {
            Products products = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            var product = context.Products.Find(id);
            ViewBag.vendorName = context.Vendors.Find(product.VendorId);
            ViewBag.CategoryName = context.Categories.Find(product.CategoryId);
            ViewBag.BrandName = context.Brands.Find(product.BrandId);
            return View(products);                   
                        
        }
    }
}

ApparelStoreUserPortal/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ApparelStoreUserPortal.Models;
using ApparelStoreUserPortal.Helper;
using Microsoft.AspNetCore.Http;

namespace ApparelStoreUserPortal.Controllers
{
    public class HomeController : Controller
    {
        private readonly OnlineApparelStoreDbContext context;
        public HomeController(OnlineApparelStoreDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {          
            var products = context.Products.ToList();
            int j = 0;
            var cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int i = 0;
            if (cart != null)
            {
                foreach (var item in cart)
                {
                    i++;
                }
                if(i !=0)
                {
                    foreach(var item in cart)
                    {
                        j++;
                    }
                    HttpContext.Session.SetString("cartitem", i.ToString());
                }
              
            }         
            return View(products);
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult logout()
        {
            HttpContext.Session.Remove("cartitem");
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", null);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cus", null);
            HttpContext.Session.Remove("name");        
            return RedirectToAction("index");
           
        }
        public IActionResult userProfile()
        {
            Customers customers = SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session, "cus");
            ViewBag.Customers = customers;
            int a = customers.CustomerId;
            ViewBag.id = a;
            return View(customers);
        }
        [HttpGet]
        public IActionResult EditProfile()
        {
            Customers cust = SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session, "cus");
            return View(cust);
        }
        [HttpPost]
        public IActionResult EditProfile(int id,Customers customers)
        {
            Customers customer1 = SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session, "cus");
            Customers customer = context.Customers.Where(x => x.Email == customer1.Email).SingleOrDefault();
            customer.CustomerFirstName = customers.CustomerFirstName;
            customer.CustomerLastName = customers.CustomerLastName;
            customer.UserName = customers.UserName;
            customer.Gender = customers.Gender;
            customer.PhoneNumber = customers.PhoneNumber;
            customer.Country = customers.Country;
            customer.State = customers.State;
            customer.ZipCode = customers.ZipCode;
            customer.Address = customers.Address;
            customer.Address2 = customers.Address2;          
            customer.AlternatePhoneNumber = customers.AlternatePhoneNumber;
            customer.Country2 = customers.Country2;
            customer.State2 = customers.State2;
            customer.ZipCode2 = customers.ZipCode2;
            context.SaveChanges();
            return RedirectToAction("userProfile","home",new { @id=customer.Email});
        }
        public IActionResult CustomerHistory()
        {
            Customers c = SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session,"cus");
            List<Orders> orders = context.Orders.Where(x=>x.CustomerId==c.CustomerId).ToList();
            ViewBag.ord = orders;       
            return View();
        }
        public IActionResult orderDetails(int id)
        {
            List<OrderProducts> orderProducts = new List<OrderProducts>();
            List<Products> products = new List<Products>();
            orderProducts = context.OrderProducts.Where(x => x.OrderId == id).ToList();
            foreach(var item in orderProducts)
            {
                Products p = context.Products.Where(x => x.ProductId == item.ProductId).SingleOrDefault();
                products.Add(p);
            }
            ViewBag.pro = products;
            return View();
        }
        [HttpGet]
        public IActionResult EditPassword()
        {
            return View();
        }
        [HttpPost]
        public IActionResult EditPassword(string oldpassword, string newpassword, string newpassword1)
        {

            Customers c = SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session, "cus");
            if (oldpassword == c.Password && newpassword == newpassword1)
            {
                Customers cus = context.Customers.Where(x => x.Email == c.Email).SingleOrDefault();
                cus.Password = newpassword;
                context.SaveChanges();
                return RedirectToAction("logout", "home");
            }

            return RedirectToAction("index");
        }
        [HttpGet]
        public IActionResult Feedback()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Feedback(FeedBacks feedBacks)
        {
            Customers c = SessionHelper.GetObjectFromJson<Customers>(HttpContext.Session, "cus");
            feedBacks.CustomerId = c.CustomerId;
            feedBacks.Message = feedBacks.Message;
            context.FeedBacks.Add(feedBacks);
            context.SaveChanges();
            return RedirectToAction("UserProfile", "Cart", new { @id = c.Email });
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Invalid()
        {
            return View();
        }
    }
}

                    

ApparelStoreUserPortal/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    <link rel="stylesheet" href="~/css/About.css" />
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
}
<div class="image-aboutus-banner">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="lg-text">About Us</h1>
                <p class="image-aboutus-para">..Online Apparel Store..</p>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <!-- Blog Post Content Column -->
        <div class="col-lg-12">
            <hr />
            <h2>Enrich your shopping list wisely.</h2>
            <hr />
            <!-- Preview Image -->
            <img class="img-responsive" src="http://mobilebusinessinsights.com/wp-content/uploads/2016/03/IBM_MobileFirst_SXSWBlog_0321_v2.jpg" alt="">
            <!-- Post Content -->
            <p class="lead">
                Online shopping is a form of electronic commerce which allows consumer to directly buy products or services from a seller over the Internet using a web browser.
            </p>
            <p> An online shop evokes the physical analogy of buying products or services at a bricks-and-mortar retailer or shopping center; the process is called business-to-consumer(B2C) online shopping.</p>
            <p>And E-commerce platforms are growing day by day.</p>
            <hr>
        </div>
        @*<!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Blog Search Well -->
                <div class="well bgcolor-skyblue">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input class="form-control" type="text">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>
                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Social Links</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled" class="social-icons">
                                <li>
                                    <a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
                                </li>
                                @*<li>
                                    <a href="#">Category Name</a>
                                </li>
                                <li>
                                    <a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
                                </li>
                                @*<li>
                                    <a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <div class="col-lg-6">
                            <ul class="list-unstyled" class="social-icons">
                                <li>
                                    <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
                                </li>
                                @*<li>
                                    <a href="#">Category Name</a>
                                </li>
                                <li>
                                    <a href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
                                </li>
                                <li>
                                    <a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <!-- /.row -->
                </div>*@
        <!-- Side Widget Well -->
        @*<div class="well bgcolor-skyblue">
                <h4>Side Widget Well</h4>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
            </div>*@
    </div>
</div>


<div class="card well">
    <h3><span class="glyphicon glyphicon-cog "></span> <b>Social Links</b> </h3>
    <div class="row">
        @*<div class="col-md-3 col-sm-3 col-xs-12 Tpadding10">*@
        <a class="col-md-3" href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
        <a class="col-md-3" href="https://twitter.com/">
            <i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></aclass="col-md-3">
            <a class="col-md-3" href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
            <a class="col-md-3" href="mailto:bootsnipp@gmail.com"><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
            @*</div>*@
    </div>
</div>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

ApparelStoreUserPortal/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}
<!doctype html>
@*<html>
<head>
    <title>Contact Us</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
   <link rel="stylesheet" href="~/css/ContactUs.css" />
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>*@
    <h2>@ViewData["Title"]</h2>
    <h3>@ViewData["Message"]</h3>
    <div class="container">
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                    @*<img src="https://www.svgimages.com/svg-image/s5/man-passportsize-silhouette-icon-256x256.png" alt="stack photo" class="img">*@
                    <img src="~/images/IMG20190223114106.jpg" alt="stack photo" class="img" width="300" height="300" />
                </div>
                <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                    <div class="container" style="border-bottom:1px solid black">
                        <h2>Apparel Store</h2>
                    </div>
                    <hr>
                    <ul class="container details">
                        <li><p><span class="glyphicon glyphicon-earphone one" style="width:50px;"></span>+91 7599437873</p></li>
                        <li><p><span class="glyphicon glyphicon-envelope one" style="width:50px;"></span>somerandom@gmail.com</p></li>
                        <li><p><span class="glyphicon glyphicon-map-marker one" style="width:50px;"></span>Greater Noida</p></li>
                        <li><p><span class="glyphicon glyphicon-new-window one" style="width:50px;"></span><a href="https://accounts.google.com">www.gmail.com</p></a>
                    </ul>
                </div>
            </div>
        </div>
       </div>
@*</body>
</html>*@

ApparelStoreUserPortal/Views/Home/CustomerHistory.cshtml
@{
    ViewData["Title"] = "CustomerHistory";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

        <h2>Ordered Products </h2>
        <table class="table table-hover">
            <tr>
                <th>OrderId</th>
                <th>Order Date</th>
                <th>Order Amount</th>
                <th>Actions</th>
            </tr>

            @foreach (var item in ViewBag.ord)
            {
                <tr>
                    <td>@item.OrderId</td>
                    <td>@item.OrderDate</td>
                    <td>@item.OrderAmount</td>
                    <td><a class="btn btn-secondary" asp-action="orderDetails" asp-controller="home" asp-route-id="@item.OrderId">View Product</a></td>
                </tr>
            }
        </table>
        <a class="btn btn-info" asp-controller="Home" asp-action="userProfile" asp-route-id="">Back to List</a>
</div>
</div>

ApparelStoreUserPortal/Views/Home/EditPassword.cshtml
@{
    ViewData["Title"] = "EditPassword";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="list-group ">
                <a href="#" class="list-group-item list-group-item-action active">Dashboard</a>
                <a asp-controller="Home" asp-action="EditPassword" class="list-group-item list-group-item-action">Edit Password</a>
                <a asp-controller="Home" asp-action="EditProfile" class="list-group-item list-group-item-action">View Profile</a>
                <a asp-controller="Home" asp-action="orderDetails" class="list-group-item list-group-item-action">Order History</a>
                <a asp-controller="Home" asp-action="logout" class="list-group-item list-group-item-action">LogOut</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Edit Your Password</h4>
                            <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <form class="form-signin" method="post" asp-controller="home" asp-action="EditPassword">
                                <div class="form-label-group">
                                    <input type="text" name="oldpassword" class="form-control" placeholder="old Password" required autofocus>
                                    <label for="username" class="sr-only">Old PassWord</label>
                                </div>
                                <br />
                                <div class="form-label-group">
                                    <input type="text" name="newpassword" class="form-control" placeholder="New password" required>
                                    <label for="password" class="sr-only">New Password</label>
                                </div>
                                <br />
                                <div class="custom-control custom-checkbox mb-3">
                                    <input type="password" name="newpassword1" class="form-control" placeholder="confirmpassword" required>
                                    <label class="custom-control-label" for="password">confirm password</label>
                                </div>
                                <br />
                                <button class="btn btn-lg btn-primary btn-block" type="submit">Update Password</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
</div>
</div>





@*<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="~/js/jquery-1.11.1.min.js"></script>*@
@*<div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Change Password</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6 col-sm-offset-3">
                <p class="text-center">Use the form below to change your password. Your password cannot be the same as your username.</p>
                <form class="form-signin" method="post" asp-controller="home" asp-action="EditPassword">
                    <div class="form-label-group">
                        <input type="text" name="oldpassword" class="form-control" placeholder="old Password" required autofocus>
                        <label for="username" class="sr-only">Old PassWord</label>
                    </div>
                    <br />
                    <div class="form-label-group">
                        <input type="password" class="input-lg form-control" name="password1" id="password1" placeholder="New Password" autocomplete="off">
                        <div class="row">
                            <div class="col-sm-6">
                                <span id="8char" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 8 Characters Long<br>
                                <span id="ucase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Uppercase Letter
                            </div>
                            <div class="col-sm-6">
                                <span id="lcase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Lowercase Letter<br>
                                <span id="num" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Number
                            </div>
                        </div>
                        <label for="password" class="sr-only">New Password</label>
                    </div>
                    <br />
                    <div class="custom-control custom-checkbox mb-3">
                        <input type="password" class="input-lg form-control" name="password2" id="password2" placeholder="Repeat Password" autocomplete="off">
                        <div class="row">
                            <div class="col-sm-12">
                                <span id="pwmatch" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> Passwords Match
                            </div>
                        </div>
                        <label class="custom-control-label" for="password">confirm password</label>
                    </div>
                    <br />
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Update Password</button>
                </form>
            </div>
        </div>
    </div>


    js




    $("input[type=password]").keyup(function () {
        var ucase = new RegExp("[A-Z]+");
        var lcase = new RegExp("[a-z]+");
        var num = new RegExp("[0-9]+");

        if ($("#password1").val().length >= 8) {
            $("#8char").removeClass("glyphicon-remove");
            $("#8char").addClass("glyphicon-ok");
            $("#8char").css("color", "#00A41E");
        } else {
            $("#8char").removeClass("glyphicon-ok");
            $("#8char").addClass("glyphicon-remove");
            $("#8char").css("color", "#FF0004");
        }

        if (ucase.test($("#password1").val())) {
            $("#ucase").removeClass("glyphicon-remove");
            $("#ucase").addClass("glyphicon-ok");
            $("#ucase").css("color", "#00A41E");
        } else {
            $("#ucase").removeClass("glyphicon-ok");
            $("#ucase").addClass("glyphicon-remove");
            $("#ucase").css("color", "#FF0004");
        }

        if (lcase.test($("#password1").val())) {
            $("#lcase").removeClass("glyphicon-remove");
            $("#lcase").addClass("glyphicon-ok");
            $("#lcase").css("color", "#00A41E");
        } else {
            $("#lcase").removeClass("glyphicon-ok");
            $("#lcase").addClass("glyphicon-remove");
            $("#lcase").css("color", "#FF0004");
        }

        if (num.test($("#password1").val())) {
            $("#num").removeClass("glyphicon-remove");
            $("#num").addClass("glyphicon-ok");
            $("#num").css("color", "#00A41E");
        } else {
            $("#num").removeClass("glyphicon-ok");
            $("#num").addClass("glyphicon-remove");
            $("#num").css("color", "#FF0004");
        }

        if ($("#password1").val() == $("#password2").val()) {
            $("#pwmatch").removeClass("glyphicon-remove");
            $("#pwmatch").addClass("glyphicon-ok");
            $("#pwmatch").css("color", "#00A41E");
        } else {
            $("#pwmatch").removeClass("glyphicon-ok");
            $("#pwmatch").addClass("glyphicon-remove");
            $("#pwmatch").css("color", "#FF0004");
        }
    });*@

ApparelStoreUserPortal/Views/Home/Feedback.cshtml
@model ApparelStoreUserPortal.Models.FeedBacks
@{
    ViewData["Title"] = "Feedback";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<div class="container">
    <div class="row">
        <div class="col-md-3 ">
            <div class="list-group ">
                <a href="#" class="list-group-item list-group-item-action active">Dashboard</a>
                <a asp-controller="Home" asp-action="EditPassword" class="list-group-item list-group-item-action">Edit Password</a>
                <a asp-controller="Home" asp-action="EditProfile" class="list-group-item list-group-item-action">View Profile</a>
                <a asp-controller="Home" asp-action="Feedback" class="list-group-item list-group-item-action">FeedBack</a>
                <a asp-controller="Home" asp-action="logout" class="list-group-item list-group-item-action">LogOut</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Your FeedBack Matters To Us..</h4>
                            <hr>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div>
                                <form asp-action="Feedback" asp-controller="Home">
                                    <div class="form-group">
                                        <label for="Message">Message</label>
                                        <input type="text" class="form-control" placeholder="Description" asp-for="Message">
                                    </div>
                                    <a class="btn btn-primary" asp-action="userProfile" asp-controller="Home">Submit</a>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
</div>

ApparelStoreUserPortal/Views/Home/Index.cshtml
@model IEnumerable<ApparelStoreUserPortal.Models.Products>
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Apparel Store</h1>
        <p class="lead text-muted">
            Online shopping is a form of electronic commerce which allows consumer to directly buy products or services from a seller over the Internet using a web browser.
            An online shop evokes the physical analogy of buying products or services at a bricks-and-mortar retailer or shopping center; the process is called business-to-consumer (B2C) online shopping.
            And E-commerce platforms are growing day by day.
        </p>
        <p>
            <a asp-controller="home" asp-action="about" class="btn btn-secondary my-2">About Us</a>
            <a asp-controller="home" asp-action="contact" class="btn btn-secondary my-2">Contact Us</a>
        </p>
    </div>
</section>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                @*thumnail start*@
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <img src="@item.ProductImage" class="bd-placeholder-img card-img-top" width="100" height="200"/>
                    
                        <div class="card-body">
                            <p class="card-text" style="font-weight:bold;">@item.ProductName</p>
                            <p class="card-text">@item.ProductDescription</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
             
                                    <a asp-controller="Detail" asp-action="Display" asp-route-id="@item.ProductId" class="btn btn-sm btn-outline-secondary">View Details</a>
                                    <a asp-controller="Cart" asp-action="buy" asp-route-id="@item.ProductId" id="demo" onclick=myFunction(); class="btn btn-outline-secondary">Add To Cart</a> 
                                    <script>
                                        function myFunction() {
                                            if (@item.ProductQuantity == 0) {
                                                alert("Product is not Available")
                                            }
                                            else
                                            {
                                               alert("Product Added successfully")
                                            }                                            
                                        }
                                    </script>
                                </div>
                                <small class="text-muted"> @item.ProductQuantity (Pcs)</small>
                            </div>
                        </div>
                    </div>
                </div>
                @*thumbnail end*@
            }


        </div>
    </div>
</div>

ApparelStoreUserPortal/Views/Home/Invalid.cshtml
@{
    ViewData["Title"] = "Invalid";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Password Entered by you is Incorrect.</h2>
<h4>Kindly enter the password</h4>

<a asp-controller="home" asp-action="index" class="btn btn-secondary">Home</a>

ApparelStoreUserPortal/Views/Home/orderDetails.cshtml
@{
    ViewData["Title"] = "orderdetail";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    <link href="~/css/modal.css" />
}

            <h2>Products</h2>
            <table class="table table-hover">
                <tr>
                    <th>ProductId</th>
                    <th>ProductName</th>
                    <th>Action</th>
                </tr>

                @foreach (var item in ViewBag.pro)
                {
                    <tr>
                        <td>@item.ProductId</td>
                        <td>@item.ProductName</td>
                        <td><a asp-controller="Detail" asp-action="Display" class="btn btn-info" asp-route-id="@item.ProductId">ProductDetails</a></td>
                    </tr>
                }
            </table>
            <a asp-controller="home" asp-action="CustomerHistory" class="btn btn-info">back</a>
            <br />