CoreApparelManagerPortal/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreApparelManagerPortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreApparelManagerPortal.Controllers
{
    public class BrandController : Controller
    {
        OnlineApparelStoreDbContext context;
        public BrandController(OnlineApparelStoreDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            var ind = context.Brands.ToList();
            return View(ind);
        }
        [HttpGet]
        public ViewResult Create()//view not created
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind("BrandName")]Brands B)
        {
            if (ModelState.IsValid)
            {
                context.Brands.Add(B);
                context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(B);

        }
        public ActionResult Delete(int id)
        {
            Brands ban = context.Brands.Find(id);
            return View(ban);
        }
        [HttpPost]
        public ActionResult Delete(int id, Brands b1)
        {
            Brands b = context.Brands.Where(x => x.BrandId == id).SingleOrDefault();
            context.Brands.Remove(b);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Brands ban = context.Brands.Where(x => x.BrandId == id).SingleOrDefault();
            return View(ban);
        }
        [HttpPost]
        public ActionResult Edit(int id, Brands b1)
        {
            Brands b = context.Brands.Where(x => x.BrandId == b1.BrandId).SingleOrDefault();
            context.Entry(b).CurrentValues.SetValues(b1);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            Brands b = context.Brands.Where(x => x.BrandId == id).SingleOrDefault();
            return View(b);
        }
    }
}

CoreApparelManagerPortal/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreApparelManagerPortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreApparelManagerPortal.Controllers
{
    public class CategoryController : Controller
    {
        OnlineApparelStoreDbContext context;
        public CategoryController(OnlineApparelStoreDbContext _context)
        {
            context = _context;
        }
        public ViewResult Index()
        {
            var cat = context.Categories.ToList();
            return View(cat);
        }
        [HttpGet]
        public ViewResult Create()//view not created
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind("CategoryName")]Categories C)
        {
            if (ModelState.IsValid)
            {
                context.Categories.Add(C);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(C);
        }
        public ActionResult Delete(int id)
        {
            Categories cat = context.Categories.Find(id);
            return View(cat);
        }
        [HttpPost]
        public ActionResult Delete(int id, Categories c1)
        {
            Categories c = context.Categories.Where(x => x.CategoryId == id).SingleOrDefault();
            context.Categories.Remove(c);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Categories cat = context.Categories.Where(x => x.CategoryId == id).SingleOrDefault();
            return View(cat);
        }
        [HttpPost]
        public ActionResult Edit(int id, Categories c1)
        {
            Categories c = context.Categories.Where(x => x.CategoryId == c1.CategoryId).SingleOrDefault();
            context.Entry(c).CurrentValues.SetValues(c1);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            Categories c = context.Categories.Where(x => x.CategoryId == id).SingleOrDefault();
            return View(c);
        }
    }
}

CoreApparelManagerPortal/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreApparelManagerPortal.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CoreApparelManagerPortal.Controllers
{
    public class ProductController : Controller
    {
        OnlineApparelStoreDbContext context;
        public ProductController(OnlineApparelStoreDbContext _context)
        {
            context = _context;
        }
        public ViewResult Index()
        {
            var pro = context.Products.ToList();
            return View(pro);
        }
        [HttpGet]
        public ViewResult Create()
        {
            ViewBag.category = new SelectList(context.Categories, "CategoryId", "CategoryName");
            ViewBag.vendor = new SelectList(context.Vendors, "VendorId", "VendorName");
            ViewBag.brand = new SelectList(context.Brands, "BrandId", "BrandName");
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind("ProductName", "ProductPrice", "ProductQuantity", "ProductSize")]Products c)
        {
            if (ModelState.IsValid)
            {
                context.Products.Add(c);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(c);

        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Products pro = context.Products.Find(id);
            return View(pro);
        }
        [HttpPost]
        public ActionResult Delete(int id, Products P1)
        {
            Products p = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            context.Products.Remove(p);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Products p = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            ViewBag.category = new SelectList(context.Categories, "CategoryId", "CategoryName", p.CategoryId);
            ViewBag.vendor = new SelectList(context.Vendors, "VendorId", "VendorName", p.VendorId);
            ViewBag.brand = new SelectList(context.Brands, "BrandId", "BrandName", p.BrandId);
            return View(p);
        }
        [HttpPost]
        public ActionResult Edit(int id, Products p1)
        {
            Products p = context.Products.Where(x => x.ProductId == p1.ProductId).SingleOrDefault();
            context.Entry(p).CurrentValues.SetValues(p1);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            Products p = context.Products.Where(x => x.ProductId == id).SingleOrDefault();
            return View(p);
        }
    }
}

CoreApparelManagerPortal/Controllers/VendorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreApparelManagerPortal.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreApparelManagerPortal.Controllers
{
    public class VendorController : Controller
    {
        OnlineApparelStoreDbContext context;
        public VendorController(OnlineApparelStoreDbContext _context)
        {
            context = _context;
        }
        public IActionResult Index()
        {
            var ven = context.Vendors.ToList();
            return View(ven);
        }
        [HttpGet]
        public ViewResult Create()//view not created
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create([Bind("VendorName", "VendorEmail", "VendorPhoneNo")]Vendors V)
        {
            if (ModelState.IsValid)
            {
                context.Vendors.Add(V);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(V);

        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Vendors ven = context.Vendors.Find(id);
            return View(ven);
        }
        [HttpPost]
        public ActionResult Delete(int id, Vendors ven)
        {
            var v = context.Vendors.Where(x => x.VendorId == id).SingleOrDefault();
            context.Vendors.Remove(v);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Vendors vendor = context.Vendors.Where(x => x.VendorId == id).SingleOrDefault();
            return View(vendor);
        }
        [HttpPost]
        public ActionResult Edit(int id, Vendors v1)
        {
            Vendors v = context.Vendors.Where(x => x.VendorId == v1.VendorId).SingleOrDefault();
            context.Entry(v).CurrentValues.SetValues(v1);
            context.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult Details(int id)
        {
            Vendors v = context.Vendors.Where(x => x.VendorId == id).SingleOrDefault();
            return View(v);
        }
    }
}

CoreApparelManagerPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreApparelManagerPortal</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CoreApparelManagerPortal</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - CoreApparelManagerPortal</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CoreApparelManagerPortal/Views/Shared/_ManagerLayout.cshtml
@using Microsoft.AspNetCore.Http;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OnlineApparelStore-Manager Portal</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/Starter.css" />
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
        <li class="nav-item">
            <img src="~/images/images.png" width="72" height="72" />
        </li>
        <a class="navbar-brand" href="#">   ApparelStore</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Category" asp-action="Index">Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Vendor" asp-action="Index">Vendors</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Brand" asp-action="Index">Brands</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Product" asp-action="Index">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Feedback" asp-action="Index">FeedBacks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Customer" asp-action="Index">Customers</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <label class="form-control">Welcome @Context.Session.GetString("uname")!!</label>
                &nbsp;
                <a asp-action="logout" asp-controller="account" class="btn btn-secondary">Logout</a>
            </form>
        </div>
    </nav>
    <main role="main" class="container">

        <div class="starter-template">
            @RenderBody()

        </div>
        <hr />
    </main><!-- /.container -->

    <footer class="container">
        <p>&copy; 2019-ApparelStore</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>